export const STATUS_DEFINITIONS: Record<string, {
    name: string;
    type: 'buff' | 'debuff';
    stackLimit: number;
    flags: string[];
    desc?: string;
    statModifiers: {
        offense?: number;
        defense?: number;
        speed?: number; // can be multiplier (1.25) or additive
        speedAdd?: number;
        tenacity?: number;
        potency?: number;
        critChance?: number;
        critDamage?: number;
    };
}> = {
    // Buffs
    'Offense Up': { name: 'Offense Up', type: 'buff', stackLimit: 1, flags: [], statModifiers: { offense: 1.5 }, desc: 'Increases Offense by 50%' },
    'Health Up': { name: 'Health Up', type: 'buff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Increases Max Health effectiveness and incoming healing potency while active' },
    'Defense Up': { name: 'Defense Up', type: 'buff', stackLimit: 1, flags: [], statModifiers: { defense: 1.5 }, desc: 'Increases Defense by 50%' },
    'Speed Up': { name: 'Speed Up', type: 'buff', stackLimit: 1, flags: [], statModifiers: { speed: 1.25 }, desc: 'Increases Speed by 25%' },
    'Tenacity Up': { name: 'Tenacity Up', type: 'buff', stackLimit: 1, flags: ['tenacity_up'], statModifiers: { tenacity: 0.5 }, desc: 'Base chance to resist harmful effects drastically increased' },
    'Potency Up': { name: 'Potency Up', type: 'buff', stackLimit: 1, flags: [], statModifiers: { potency: 0.5 }, desc: 'Base chance to apply harmful effects drastically increased' },
    'Critical Chance Up': { name: 'Critical Chance Up', type: 'buff', stackLimit: 1, flags: [], statModifiers: { critChance: 0.25 }, desc: 'Critical Hit Chance increased by 25%' },
    'Critical Damage Up': { name: 'Critical Damage Up', type: 'buff', stackLimit: 1, flags: [], statModifiers: { critDamage: 0.5 }, desc: 'Critical Damage multiplier increased by 50%' },
    'Advantage': { name: 'Advantage', type: 'buff', stackLimit: 1, flags: ['guaranteed_crit', 'consume_on_attack'], statModifiers: {}, desc: 'Next attack is a guaranteed Critical Hit' },
    'Retribution': { name: 'Retribution', type: 'buff', stackLimit: 1, flags: ['counterattack'], statModifiers: {}, desc: 'Counterattacks instantly whenever damaged' },
    'Stealth': { name: 'Stealth', type: 'buff', stackLimit: 1, flags: ['stealth'], statModifiers: {}, desc: 'Cannot be directly targeted unless all allies are Stealthed' },
    'Taunt': { name: 'Taunt', type: 'buff', stackLimit: 1, flags: ['taunt'], statModifiers: {}, desc: 'Forces enemies to target this unit' },
    'Foresight': { name: 'Foresight', type: 'buff', stackLimit: 1, flags: ['evade_next', 'consume_on_evade'], statModifiers: {}, desc: 'Evades the next attack completely' },
    'Damage Immunity': { name: 'Damage Immunity', type: 'buff', stackLimit: 1, flags: ['damage_immunity'], statModifiers: {}, desc: 'Immune to all direct damage' },
    'Heal Over Time': { name: 'Heal Over Time', type: 'buff', stackLimit: 99, flags: ['heal_on_turn_start'], statModifiers: {}, desc: 'Recovers Health at the start of next turn' },
    'Protection Up': { name: 'Protection Up', type: 'buff', stackLimit: 1, flags: ['bonus_protection'], statModifiers: {}, desc: 'Granted a layer of Bonus Protection' },
    'Protection Over Time': { name: 'Protection Over Time', type: 'buff', stackLimit: 99, flags: [], statModifiers: {}, desc: 'Recovers Protection at the start of next turn' },
    'Dramatic Entrance': { name: 'Dramatic Entrance', type: 'buff', stackLimit: 1, flags: ['immune_ability_block'], statModifiers: { speed: 1.3, offense: 1.25 }, desc: 'Immune to Ability Block. +30% Speed and +25% Offense' },
    'Inspired': { name: 'Inspired', type: 'buff', stackLimit: 1, flags: [], statModifiers: { speed: 1.1, tenacity: 0.1 }, desc: 'Boosted morale: +10% Speed and Tenacity' },
    'Unconventional Tactics': { name: 'Unconventional Tactics', type: 'buff', stackLimit: 1, flags: ['unconventional_tactics'], statModifiers: { speedAdd: 10, potency: 0.1 }, desc: '+10 Speed, +10% Potency, +10% Evasion' },
    'Intel': { name: 'Intel', type: 'buff', stackLimit: 10, flags: [], statModifiers: {}, desc: 'Enables Agent Kallus abilities' },
    'Insight': { name: 'Insight', type: 'buff', stackLimit: 20, flags: [], statModifiers: {}, desc: 'Ahsoka Tano (The Grey) mechanic' },
    'Blaze Of Glory': { name: 'Blaze Of Glory', type: 'buff', stackLimit: 1, flags: ['blaze_of_glory', 'prevent_prot_recovery'], statModifiers: { offense: 1.3, critDamage: 0.2, defense: 0.8 }, desc: '+30% Offense, +20% Critical Damage, Ignore 25% Defense, -20% Defense, Cannot gain Protection Up' },
    'Reanimated': { name: 'Reanimated', type: 'buff', stackLimit: 1, flags: ['reanimated'], statModifiers: {}, desc: 'Upon defeat: Revive with 20% Health, Remove Reanimated' },
    'Analysis': { name: 'Analysis', type: 'buff', stackLimit: 20, flags: [], statModifiers: { speedAdd: 2 }, desc: '+2 Speed, +2% Mastery per stack' },
    'Entrenched': { name: 'Entrenched', type: 'buff', stackLimit: 1, flags: ['entrenched', 'prevent_tm_reduction'], statModifiers: { defense: 1.4, speedAdd: -20 }, desc: '+40% Defense, -20 Speed, Immune to Turn Meter Reduction, Take 25% reduced AoE Damage' },
    'Veteran Orders': { name: 'Veteran Orders', type: 'buff', stackLimit: 1, flags: ['veteran_orders', 'prevent_crit'], statModifiers: {}, desc: 'Cannot be Critically Hit, Take 25% reduced AoE Damage' },
    'Resolve': { name: 'Resolve', type: 'buff', stackLimit: 10, flags: [], statModifiers: { defense: 0.05, offense: 0.03 }, desc: '+5% Defense, +3% Offense per stack' },
    'Ultimate Stance': { name: 'Ultimate Stance', type: 'buff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Unit is in Ultimate Stance with enhanced combat capabilities' },
    'bonus_turn': { name: 'bonus_turn', type: 'buff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Granted a Bonus Turn' },

    // Debuffs
    'Ability Block': { name: 'Ability Block', type: 'debuff', stackLimit: 1, flags: ['prevent_special'], statModifiers: {}, desc: 'Cannot use Special or Ultimate abilities' },
    'Analyze': { name: 'Analyze', type: 'debuff', stackLimit: 1, flags: [], statModifiers: { defense: 0.8 }, desc: 'Defense reduced by 20% due to tactical analysis' },
    'Bribed': { name: 'Bribed', type: 'debuff', stackLimit: 1, flags: ['prevent_counter'], statModifiers: {}, desc: 'Cannot counterattack. Action undermined by the cartel' },
    'Intimidated': { name: 'Intimidated', type: 'debuff', stackLimit: 1, flags: ['prevent_counter'], statModifiers: { offense: 0.5 }, desc: 'Offense halved and cannot counterattack' },
    'Target Lock': { name: 'Target Lock', type: 'debuff', stackLimit: 1, flags: ['prevent_stealth'], statModifiers: {}, desc: 'Cannot gain Stealth and takes enhanced effects from certain attacks' },
    'Vulnerable': { name: 'Vulnerable', type: 'debuff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Any attack against this unit is a guaranteed Critical Hit' },
    'Blind': { name: 'Blind', type: 'debuff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Next attack is guaranteed to Evade/Miss' },
    'Plague': { name: 'Plague', type: 'debuff', stackLimit: 99, flags: ['damage_on_turn_start_dot'], statModifiers: {}, desc: 'Takes damage equivalent to 5% Max Health at start of turn. Dispelled only when healed to Full Health' },
    'Thermal Detonator': { name: 'Thermal Detonator', type: 'debuff', stackLimit: 99, flags: [], statModifiers: {}, desc: 'Explodes dynamically, heavily damaging the victim' },
    'Isolation': { name: 'Isolation', type: 'debuff', stackLimit: 1, flags: ['prevent_buff', 'prevent_assist'], statModifiers: {}, desc: 'Cannot gain Buffs, assist, or counterattack. Cannot be targeted by ally abilities' },
    'Healing Immunity': { name: 'Healing Immunity', type: 'debuff', stackLimit: 1, flags: ['prevent_heal'], statModifiers: {}, desc: 'HP cannot be recovered' },
    'Buff Immunity': { name: 'Buff Immunity', type: 'debuff', stackLimit: 1, flags: ['prevent_buff'], statModifiers: {}, desc: 'Cannot gain any positive status effects' },
    'Defense Down': { name: 'Defense Down', type: 'debuff', stackLimit: 1, flags: [], statModifiers: { defense: 0.5 }, desc: 'Defense reduced by 50%' },
    'Offense Down': { name: 'Offense Down', type: 'debuff', stackLimit: 1, flags: [], statModifiers: { offense: 0.5 }, desc: 'Offense reduced by 50%' },
    'Speed Down': { name: 'Speed Down', type: 'debuff', stackLimit: 1, flags: [], statModifiers: { speed: 0.75 }, desc: 'Speed reduced by 25%' },
    'Potency Down': { name: 'Potency Down', type: 'debuff', stackLimit: 1, flags: [], statModifiers: { potency: -0.5 }, desc: 'Potency reduced by 50%' },
    'Tenacity Down': { name: 'Tenacity Down', type: 'debuff', stackLimit: 1, flags: [], statModifiers: { tenacity: -0.5 }, desc: 'Tenacity reduced by 50%. Cannot resist debuffs.' },
    'Daze': { name: 'Daze', type: 'debuff', stackLimit: 1, flags: ['prevent_assist', 'prevent_counter'], statModifiers: {}, desc: 'Cannot assist, counterattack, or gain bonus Turn Meter' },
    'Stun': { name: 'Stun', type: 'debuff', stackLimit: 1, flags: ['skip_turn', 'prevent_assist', 'prevent_counter'], statModifiers: {}, desc: 'Misses their next turn completely' },
    'Fear': { name: 'Fear', type: 'debuff', stackLimit: 1, flags: ['skip_turn', 'take_damage_on_expiration', 'prevent_assist', 'prevent_counter'], statModifiers: {}, desc: 'Misses next turn. If damaged, Fear breaks and deals bonus damage' },
    'Exposed': { name: 'Exposed', type: 'debuff', stackLimit: 1, flags: ['bonus_damage_on_hit', 'consume_on_hit'], statModifiers: {}, desc: 'Takes bonus damage equivalent to 10% Max HP when damaged next' },
    'Burning': { name: 'Burning', type: 'debuff', stackLimit: 1, flags: ['damage_on_turn_start'], statModifiers: {}, desc: 'Takes Burn damage equal to 15% Max HP at start of turn' },
    'Marked': { name: 'Marked', type: 'debuff', stackLimit: 1, flags: ['marked', 'override_stealth'], statModifiers: {}, desc: 'Forces enemies to target this unit regardless of Stealth or Taunt' },
    'Marked Target': { name: 'Marked Target', type: 'debuff', stackLimit: 1, flags: ['marked', 'override_stealth'], statModifiers: {}, desc: 'Forces enemies to target this unit regardless of Stealth or Taunt. Triggers Red Squadron synergies.' },
    'Pursued': { name: 'Pursued', type: 'debuff', stackLimit: 1, flags: ['prevent_stealth'], statModifiers: {}, desc: 'Cannot gain Stealth' },
    'Purge': { name: 'Purge', type: 'debuff', stackLimit: 6, flags: [], statModifiers: { tenacity: -0.05 }, desc: 'Consumed by Inquisitors for devastating effects' },
    'Order 66': { name: 'Order 66', type: 'debuff', stackLimit: 10, flags: ['take_bonus_damage_kf'], statModifiers: {}, desc: 'Irrevocable target. Lord Vader manipulates this status directly' },
    'Frostbite': { name: 'Frostbite', type: 'debuff', stackLimit: 4, flags: ['lose_tm_on_action'], statModifiers: { speedAdd: -5 }, desc: 'Loses fixed Speed and Turn Meter' },
    'Damage Over Time': { name: 'Damage Over Time', type: 'debuff', stackLimit: 99, flags: ['damage_on_turn_start_dot'], statModifiers: {}, desc: 'Takes damage equivalent to 5% Max HP at start of turn per stack' },
    'Shattered Defense': { name: 'Shattered Defense', type: 'debuff', stackLimit: 1, flags: [], statModifiers: { defense: 0.2 }, desc: 'Armor critically compromised (Defense reduced to 20%)' },
    'Shock': { name: 'Shock', type: 'debuff', stackLimit: 1, flags: ['prevent_heal', 'prevent_prot_recovery', 'prevent_tm_gain', 'prevent_buff'], statModifiers: {}, desc: 'Cannot heal, recover protection, gain buffs, or gain Turn Meter' },
    'Whiteout': { name: 'Whiteout', type: 'buff', stackLimit: 1, flags: ['whiteout', 'evade_next_attack'], statModifiers: { tenacity: 0.1 }, desc: 'Evades the next attack completely' },
    'Predicted': { name: 'Predicted', type: 'debuff', stackLimit: 1, flags: ['predicted'], statModifiers: {}, desc: 'When this unit would take a turn: Remove Predicted, Grand Admiral Thrawn gains Bonus Turn' },
    'Battlefield Corruption': { name: 'Battlefield Corruption', type: 'debuff', stackLimit: 1, flags: ['battlefield_corruption', 'damage_on_turn_start'], statModifiers: {}, desc: 'Take damage at start of turn, Receive 50% reduced healing' },
    'Suppressed': { name: 'Suppressed', type: 'debuff', stackLimit: 1, flags: ['suppressed', 'prevent_bonus_tm'], statModifiers: { critChance: -0.2, speedAdd: -20 }, desc: '-20% Critical Chance, -20 Speed, Cannot gain Bonus Turn Meter' },
    'Momentum': { name: 'Momentum', type: 'buff', stackLimit: 20, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: { offense: 1.01, speedAdd: 1 }, desc: '+1% Offense and +1 Speed per stack (max 20). Cannot be dispelled, copied or prevented.' },
    'Pathfinder': { name: 'Pathfinder', type: 'buff', stackLimit: 1, flags: ['taunt', 'prevent_cleanse', 'prevent_copy', 'pathfinder'], statModifiers: {}, desc: 'Taunt. Cannot lose Taunt. Cannot be dispelled. On reaching 0 Protection, removed and unit gains Fatigued.' },
    'Fatigued': { name: 'Fatigued', type: 'debuff', stackLimit: 1, flags: ['skip_turn', 'prevent_assist', 'prevent_counter', 'untargetable', 'damage_immunity', 'prevent_cleanse', 'prevent_prevent', 'fatigued'], statModifiers: {}, desc: 'Cannot Act, cannot be Targeted, cannot Take Damage, cannot Assist, cannot Counterattack. Dur: 3 turns. On expiration, recovers 100% Integrity/Protection, gains Pathfinder.' },
    'Lockdown': { name: 'Lockdown', type: 'debuff', stackLimit: 1, flags: ['prevent_special', 'prevent_assist', 'prevent_counter', 'prevent_bonus_tm', 'prevent_cleanse', 'prevent_copy', 'lockdown'], statModifiers: {}, desc: 'Cannot use Special Abilities, Assist, Counterattack, or gain bonus Turn Meter. Cannot be copied or dispelled.' },
    'Riot Control': { name: 'Riot Control', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'riot_control'], statModifiers: { defense: 1.25, tenacity: 0.25, speedAdd: 10 }, desc: '+25% Defense, +25% Tenacity, +10 Speed. Damages to Locked Down enemies recover 3% Protection and gain 2% TM. Cannot be copied or dispelled.' },
    'Combined Arms': { name: 'Combined Arms', type: 'buff', stackLimit: 3, flags: ['prevent_cleanse', 'prevent_copy'], statModifiers: {}, desc: 'Enables 212th Combined Arms Assault. Max 3 stacks. Cannot be copied or dispelled.' },
    'Negotiator': { name: 'Negotiator', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy'], statModifiers: {}, desc: 'All allied Health damage is redirected to this unit\'s Protection while it has Protection. Ignores Taunt. Cannot be copied or dispelled.' },
    'Ambushed': { name: 'Ambushed', type: 'debuff', stackLimit: 1, flags: ['marked', 'override_stealth', 'ambushed'], statModifiers: {}, desc: 'Double target status. Cannot be copied or dispelled.' },
    'Overdisciplined': { name: 'Overdisciplined', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent', 'prevent_prot_recovery'], statModifiers: {}, desc: 'Frontline fortitude: Cannot gain Protection, Protection Up or suffer Fear. Gains 100% of Max Protection as Max Health. Gains 5% TM whenever losing 10% Health.' },
    'Hypervigilance Disorder': { name: 'Hypervigilance Disorder', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: { speedAdd: 30 }, desc: '+30 Speed. Whenever an ally takes damage, gain 5% TM. Ignores Stealth. Cannot gain bonus TM from allies.' },
    'Impulse Control Disorder': { name: 'Impulse Control Disorder', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: { offense: 1.3 }, desc: '+30% Offense, +20% Max Health. When taking damage, gain Offense Up (1 turn). When defeating an enemy, gain Daze (1 turn).' },
    'Attachment Disorder': { name: 'Attachment Disorder', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: {}, desc: 'When Bad Batch ally < 50% HP, gain 10% TM. When using specials, target heals 10% HP. Bonus turn on ally defeat. Untargetable while other Bad Batch allies active.' },
    'Obsessive Analysis Disorder': { name: 'Obsessive Analysis Disorder', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: { potency: 0.3, speedAdd: 30 }, desc: '+30% Potency, +30 Speed. Whenever a debuff expires, gain 5% TM. Taking a Bonus Turn loses 5% Max Health.' },
    'Identity Disorder': { name: 'Identity Disorder', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: {}, desc: 'Immune to Shock. +25% Critical Avoidance. Gain debuffs when allies do for 1 turn. When debuffed, recover 5% Protection.' },
    'Paranoia Disorder': { name: 'Paranoia Disorder', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: {}, desc: 'Ignore Stealth. Ignore Taunt against Marked targets. Gain 2% Offense when allies attack. Lose 2% Defense when attacking.' },
    'No Disorder': { name: 'No Disorder', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: {}, desc: 'Unaffected by Disorders. Whenever Bad Batch triggers a disorder, Batcher gains 5% TM. When attacking, random Bad Batch ally heals 5% Health. Taunt (1 turn) on Omega taking damage.' },
    'Investigation': { name: 'Investigation', type: 'debuff', stackLimit: 1, flags: ['investigation'], statModifiers: { defense: 0.8 }, desc: 'Under Jedi investigation. Certain Jedi Guardian abilities trigger bonus effects against this unit.' },
    'Arrest Warrant': { name: 'Arrest Warrant', type: 'debuff', stackLimit: 1, flags: ['arrest_warrant'], statModifiers: { speed: 0.85, defense: 0.7 }, desc: 'An active arrest warrant is issued by the Jedi Council. Jedi Guardian allies gain high offense and trigger extra combat utility.' },
    'Council Guidance': { name: 'Council Guidance', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: {}, desc: 'Guided by the Jedi High Council. Used to power up and trigger supreme team-wide effects. Cannot be copied, dispelled, or prevented.' },
    "Guardian's Resolve": { name: "Guardian's Resolve", type: 'buff', stackLimit: 10, flags: [], statModifiers: { defense: 1.05 }, desc: 'Guardian stack: +5% Defense per stack (max +50%). Reaching 10 stacks triggers full team-wide defensive burst and recovery.' },
    
        'Last Hope': { name: 'Last Hope', type: 'buff', stackLimit: 99, flags: ['prevent_cleanse'], statModifiers: { offense: 1.1 }, desc: 'Grants 10% Offense per stack. Cannot be dispelled by enemies.' },
    'Endless Legion': { name: 'Endless Legion', type: 'buff', stackLimit: 99, flags: [], statModifiers: {}, desc: 'Separatist Droid stack effect.' },
    'Tactical Advantage': { name: 'Tactical Advantage', type: 'buff', stackLimit: 99, flags: [], statModifiers: {}, desc: 'Trench mechanic.' },
    'Tactical Data': { name: 'Tactical Data', type: 'buff', stackLimit: 99, flags: [], statModifiers: {}, desc: 'Trench mechanic.' },
    'Impending Doom': { name: 'Impending Doom', type: 'buff', stackLimit: 99, flags: [], statModifiers: {}, desc: 'Trench ultimate charge mechanic.' },
    'Dark Maelstrom': { name: 'Dark Maelstrom', type: 'buff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Vader mechanic.' },
    'Rule of Two': { name: 'Rule of Two', type: 'buff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Sith mechanic.' },
    'Unlimited Power': { name: 'Unlimited Power', type: 'buff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Palpatine mechanic.' },
    'Deathmark': { name: 'Deathmark', type: 'debuff', stackLimit: 1, flags: ['marked', 'override_stealth'], statModifiers: {}, desc: 'Forces enemies to target this unit. Takes bonus damage when hit.' },
    'Elusive': { name: 'Elusive', type: 'buff', stackLimit: 1, flags: ['untargetable', 'prevent_cleanse'], statModifiers: {}, desc: 'Cannot be targeted.' },
    'Contract': { name: 'Contract', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse'], statModifiers: {}, desc: 'Bounty Hunter Contract.' },
    'Bounty': { name: 'Bounty', type: 'buff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Bounty Hunter Reward.' },
    'Unleashed': { name: 'Unleashed', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse'], statModifiers: {}, desc: 'Starkiller Unleashed.' },
    'Imperial Contract': { name: 'Imperial Contract', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse'], statModifiers: {}, desc: 'Imperial Remnant Contract.' },
    'Armor Shred': { name: 'Armor Shred', type: 'debuff', stackLimit: 99, flags: ['prevent_cleanse'], statModifiers: { defense: 0.5 }, desc: 'Defense permanently reduced.' },
    'Debt': { name: 'Debt', type: 'debuff', stackLimit: 99, flags: [], statModifiers: {}, desc: 'Hondo mechanic.' },
    'Corruption': { name: 'Corruption', type: 'debuff', stackLimit: 99, flags: [], statModifiers: {}, desc: 'Corruption mechanic.' },
    'Collector': { name: 'Collector', type: 'buff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Collector mechanic.' },
    'Infested': { name: 'Infested', type: 'debuff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Takes bonus damage.' },
    'Foil': { name: 'Foil', type: 'debuff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Foil buff/debuff mechanic.' },
    'Critical Chance Down': { name: 'Critical Chance Down', type: 'debuff', stackLimit: 1, flags: [], statModifiers: { critChance: -0.25 }, desc: 'Critical Chance reduced by 25%.' },
    'Accuracy Up': { name: 'Accuracy Up', type: 'buff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Accuracy increased.' },
    'Defense Penetration Up': { name: 'Defense Penetration Up', type: 'buff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Defense Penetration increased.' },
    'Accuracy Down': { name: 'Accuracy Down', type: 'debuff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Accuracy decreased.' },
    'Stagger': { name: 'Stagger', type: 'debuff', stackLimit: 1, flags: ['consume_on_hit'], statModifiers: {}, desc: 'Next time this unit takes damage, it loses 100% Turn Meter.' },

    // Custom Expansion Statuses
    'Information Broker': { name: 'Information Broker', type: 'debuff', stackLimit: 3, flags: ['information_broker'], statModifiers: {}, desc: 'Tracked by The Network. Triggers powerful anti-faction synergies.' },
    'Treasure': { name: 'Treasure', type: 'buff', stackLimit: 10, flags: ['treasure'], statModifiers: { offense: 1.02, potency: 0.02 }, desc: '+2% Offense and +2% Potency per stack. Triggers pirate mechanics.' },
    'Hostage': { name: 'Hostage', type: 'debuff', stackLimit: 1, flags: ['prevent_assist', 'prevent_counter', 'hostage'], statModifiers: { offense: 0.8 }, desc: '-20% Offense. Cannot Assist or Counterattack.' },
    'Payout': { name: 'Payout', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'payout'], statModifiers: {}, desc: 'Reward for completing a Corsair contract.' },
    'Raid Mark': { name: 'Raid Mark', type: 'buff', stackLimit: 10, flags: ['raid_mark'], statModifiers: {}, desc: 'Marks enemy vulnerability. Stacks to trigger Captain Ithano\'s Payout.' },
    'Secrecy': { name: 'Secrecy', type: 'buff', stackLimit: 1, flags: ['untargetable', 'prevent_copy', 'secrecy'], statModifiers: { critChance: 0.25, critDamage: 0.25 }, desc: 'Cannot be targeted directly. +25% Critical Chance, +25% Critical Damage.' },
    'Artifact': { name: 'Artifact', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy'], statModifiers: {}, desc: 'Powerful ancient relic.' },
    'Explosive Charge': { name: 'Explosive Charge', type: 'debuff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Detonates for massive damage.' },
    'Tortured': { name: 'Tortured', type: 'debuff', stackLimit: 1, flags: [], statModifiers: {}, desc: 'Exposed to interrogations. Feeds 0-0-0 mechanics.' },
    'Imperial Decree': { name: 'Imperial Decree', type: 'debuff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: { speedAdd: -10, tenacity: -0.20 }, desc: 'Designated an enemy of the Empire. -10 Speed and -20% Tenacity. Cannot be copied, dispelled, or prevented.' },
    'Dossier': { name: 'Dossier', type: 'debuff', stackLimit: 5, flags: [], statModifiers: {}, desc: 'Sought-after imperial evidence. Enables advanced ISB execution strategies and tactical debuffs.' },
    'Expose': { name: 'Expose', type: 'debuff', stackLimit: 1, flags: ['bonus_damage_on_hit', 'consume_on_hit'], statModifiers: {}, desc: 'Takes bonus damage equivalent to 10% Max HP when damaged next' },
    'Protect the Child': { name: 'Protect the Child', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'protect_the_child'], statModifiers: {}, desc: 'Rotta the Huttlet accompanies this unit. If this unit loses all Protection, the entire team suffers Offense Down until protection is restored.' },

    // Scripted / ability-named statuses previously applied or checked without definitions
    'Imperial Approval': { name: 'Imperial Approval', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy'], statModifiers: { offense: 1.15, tenacity: 0.15 }, desc: 'Emperor Palpatine holds Imperial Approval. Imperial allies recover Protection when enemies fall.' },
    'Ordered Fire': { name: 'Ordered Fire', type: 'buff', stackLimit: 1, flags: [], statModifiers: { critChance: 0.1 }, desc: 'Coordinated volley. This unit has issued or received Ordered Fire and fights with heightened coordination.' },
    // Alias recognized by AI / logs (canonical status remains Ability Block)
    'Blocked': { name: 'Blocked', type: 'debuff', stackLimit: 1, flags: ['prevent_special'], statModifiers: {}, desc: 'Alias of Ability Block. Cannot use Special or Ultimate abilities.' },

    // Imperial Architects — The Project
    'The Project': { name: 'The Project', type: 'buff', stackLimit: 99, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: {}, desc: 'Team construction progress toward the Imperial superweapon. Reaches Complete at 25 stacks. Cannot be dispelled, copied, or prevented.' },
    'The Project Complete': { name: 'The Project Complete', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: {}, desc: 'The Project has reached 25 stacks. Authority By All Means is unlocked.' },
    'Hostage Scientist': { name: 'Hostage Scientist', type: 'buff', stackLimit: 1, flags: ['prevent_cleanse', 'prevent_copy', 'prevent_prevent'], statModifiers: {}, desc: 'Galen Erso is held as the Hostage Scientist. Cannot be dispelled. Damaging him advances The Project.' }
};
